#version 150
uniform sampler2D DiffuseSampler;
uniform sampler2D LutSampler;
uniform float Intensity;
uniform vec3 LutDomainMin;
uniform vec3 LutDomainMax;
uniform vec2 ScreenSize;
uniform float Exposure;
uniform float Contrast;
uniform float Highlights;
uniform float Shadows;
uniform float Saturation;
uniform float Temperature;
uniform float Tint;
uniform float Gamma;
in vec2 texCoord;
out vec4 fragColor;
void main() {
    vec2 halfPixel = 0.5 / max(ScreenSize, vec2(1.0));
    vec4 source = texture(DiffuseSampler, clamp(texCoord, halfPixel, vec2(1.0) - halfPixel));
    vec3 original = source.rgb;
    vec3 color = original * pow(2.0, Exposure);
    color.r += Temperature * 0.05;
    color.b -= Temperature * 0.05;
    color.g += Tint * 0.05;
    color = pow(max(color, vec3(0.0)), vec3(1.0 / max(Gamma, 0.1)));
    vec2 lutDimensions = vec2(textureSize(LutSampler, 0));
    float lutSize = lutDimensions.y;
    vec3 coordinate = clamp((color - LutDomainMin) / max(LutDomainMax - LutDomainMin, vec3(0.000001)), vec3(0.0), vec3(1.0)) * (lutSize - 1.0);
    float x = (floor(coordinate.x) + floor(coordinate.y) * lutSize + 0.5) / (lutSize * lutSize);
    float y = (floor(coordinate.z) + 0.5) / lutSize;
    vec3 lut = texture(LutSampler, vec2(x, y)).rgb;
    color = lut;
    color = (color - 0.5) * (1.0 + Contrast) + 0.5;
    float luminance = dot(color, vec3(0.2126, 0.7152, 0.0722));
    float highlightMask = smoothstep(0.5, 1.0, luminance);
    float shadowMask = 1.0 - smoothstep(0.0, 0.5, luminance);
    color += Highlights * highlightMask * 0.25;
    color += Shadows * shadowMask * 0.25;
    color = mix(vec3(luminance), color, Saturation);
    fragColor = vec4(mix(original, color, clamp(Intensity, 0.0, 1.0)), source.a);
}
